dependencies = {
    'a': [],
    'accordion': ['icon'],
    'alert': [],
    'alert_dialog': ['button'],
    'allauth': [
        'card',
        'button',
        'input',
        'label',
        'checkbox',
        'alert',
        'badge',
        'separator',
    ],
    'aspect_ratio': [],
    'avatar': [],
    'badge': [],
    'breadcrumb': ['icon'],
    'button': [],
    'button_group': ['button', 'separator'],
    'card': [],
    'combobox': ['button', 'popover', 'icon'],
    'command': ['icon'],
    'command_dialog': ['command'],
    'dialog': ['button', 'icon'],
    'checkbox': [],
    'dropdown_menu': [],
    'empty': [],
    'field': ['label', 'separator'],
    'form': ['label'],
    'icon': [],
    'input': [],
    'input_group': ['button', 'input', 'textarea'],
    'item': ['separator'],
    'kbd': [],
    'label': [],
    'native_select': ['icon'],
    'navigation_menu': ['icon'],
    'popover': [],
    'progress': [],
    'select': ['icon'],
    'sheet': ['button', 'icon'],
    'separator': [],
    'skeleton': [],
    'spinner': ['icon'],
    'table': [],
    'tabs': [],
    'toast': ['icon'],
    'textarea': [],
    'typography': [],
}
