[project]
authors = [
    { name = "Marcelo Machado", email = "uniqueduckinbox@duck.com" },
    { name = "Sarthak Jariwala", email = "sarthak@sarthakjariwala.com" },
]
name = "django-shadcn"
version = "1.0.0"
description = "shadcn/ui for Django"
readme = "README.md"
requires-python = ">=3.12"
keywords = [
    "django",
    "shadcn",
    "ui",
    "django-shadcn",
    "components",
    "shadcnui",
    "library",
    "cotton",
    "alpinejs",
    "tailwindcss",
]
classifiers = [
    "Framework :: Django",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: User Interfaces",
]
dependencies = ["copier>=9.5.0", "typer>=0.15.1"]

[dependency-groups]
dev = ["ignr>=2.3", "pytest>=9.1.1", "pytest-cov>=7.1.0"]

[project.scripts]
django_shadcn = "django_shadcn.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = ["docs/", "docs/*"]
