"""Icons referenced by components have to exist as partials.

The partials are generated by scripts/generate_icons.py, which needs network
access. These checks are offline: they only compare what the markup asks for
against what is on disk.
"""

import re

ICON_USAGE = re.compile(r'<c-icon\s[^>]*name=[\'"]([a-z0-9-]+)[\'"]')

# Shipped as the component itself, not as an icon.
NOT_AN_ICON = {'index.html'}


def icons_referenced(components_root) -> set[str]:
    names: set[str] = set()

    for template in components_root.rglob('*.html'):
        names.update(ICON_USAGE.findall(template.read_text(encoding='utf-8')))

    return names


def icons_available(components_root) -> set[str]:
    return {
        path.stem.replace('_', '-')
        for path in (components_root / 'icon').glob('*.html')
        if path.name not in NOT_AN_ICON
    }


def test_components_reference_icons(components_root):
    assert icons_referenced(components_root), 'no <c-icon> usage found'


def test_every_referenced_icon_has_a_partial(components_root):
    missing = icons_referenced(components_root) - icons_available(
        components_root
    )

    assert not missing, (
        f'missing icon partials: {sorted(missing)}. '
        'Run python scripts/generate_icons.py'
    )


def test_no_unused_icon_partials(components_root):
    unused = icons_available(components_root) - icons_referenced(
        components_root
    )

    assert not unused, f'icons nothing references: {sorted(unused)}'


def test_no_inline_svg_outside_the_icon_component(components_root):
    """Icons come from lucide through <c-icon>, never pasted by hand."""
    offenders = [
        path.relative_to(components_root)
        for path in components_root.rglob('*.html')
        if path.parent.name != 'icon'
        and '<svg' in path.read_text(encoding='utf-8')
    ]

    assert not offenders, f'inline svg found in: {offenders}'
