"""
Django settings for docs project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-3472^sitrt^-xx#!u-t_4bi2ac5&6^i8%0s9!3!zyy#uf#rq44",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_htmx",
    # Cotton's default AppConfig wraps every loader in Django's cached loader
    # whatever DEBUG says, and that loader keeps a compiled template by name
    # without ever reading the file again. Editing a component then changes
    # nothing until the process restarts, and the page serves the previous
    # version with no sign that it is doing so. The loaders are declared by
    # hand below instead.
    "django_cotton.apps.SimpleAppConfig",
    "docs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "docs.urls"

# The pages render components/ out of the library this project sits in, so
# they can never drift from what the CLI installs. The library is looked for
# rather than counted up to: a fixed number of parents was right while this
# sat directly in the repository root and stopped being right the moment it
# moved.
#
# A deploy has no library above it — the host builds from this directory and
# bundles only what is inside it — so scripts/sync_components.py copies the
# components in during the build and the copy answers instead. The library is
# checked first and the copy is gitignored, so a checkout cannot end up
# rendering it: that is how the pages once spent a release showing components
# nobody had touched in weeks.
def _components():
    for candidate in BASE_DIR.parents:
        components = candidate / "components"
        if components.is_dir() and (candidate / "pyproject.toml").is_file():
            return components

    built = BASE_DIR / "components"

    if built.is_dir():
        return built

    raise ImproperlyConfigured(
        f"no components for {BASE_DIR}: run this from inside the "
        "django-shadcn checkout, or run scripts/sync_components.py first"
    )


COMPONENTS_DIR = _components()

COTTON_DIR = "components"

TEMPLATE_LOADERS = [
    "django_cotton.cotton_loader.Loader",
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

# Caching is what production wants and what local editing cannot have.
if not DEBUG:
    TEMPLATE_LOADERS = [
        ("django.template.loaders.cached.Loader", TEMPLATE_LOADERS)
    ]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Cotton resolves <c-x> under COTTON_DIR, so the directory that
        # holds components/ is what belongs here, not components/ itself.
        "DIRS": [BASE_DIR / "templates", COMPONENTS_DIR.parent],
        "OPTIONS": {
            "builtins": ["django_cotton.templatetags.cotton"],
            "loaders": TEMPLATE_LOADERS,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "docs.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("pt-br", "Português"),
    ("es", "Español"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
# Name of static files folder (after called python manage.py collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [BASE_DIR / "static"]

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
